---
- hosts: web
  gather_facts: false   
  tasks:
    - name: Install httpd
      yum: name=httpd state=installed
      become: yes
      register: temp_var
    - name: debugging
      debug: var=temp_var   
    - name: Printing Successfull Installation
      debug: msg='httpd installation is successfull'
      # when: temp_var.rc == 0
      when: temp_var is succeeded 
    - name: Printing Failure Message
      debug: msg='httpd installation failed!!'
      when: temp_var is failed 

...
